def get_domain(course):
    course_lower = course.lower()
    if any(word in course_lower for word in ['python', 'java', 'c++', 'javascript', 'programare']):
        return 2  # Programare
    if any(word in course_lower for word in ['web', 'html', 'css', 'full stack']):
        return 3  # Dezvoltare Web
    if any(word in course_lower for word in ['mobile', 'android', 'ios', 'flutter', 'react native']):
        return 4  # Dezvoltare Mobile
    if 'inteligență artificială' in course_lower or 'ai' in course_lower:
        return 5  # Inteligență Artificială
    if 'machine learning' in course_lower:
        return 6  # Machine Learning
    if 'data science' in course_lower or 'analiza datelor' in course_lower:
        return 7  # Data Science
    if any(word in course_lower for word in ['cyber', 'securitate', 'hacking']):
        return 8  # Cybersecurity
    if any(word in course_lower for word in ['cloud', 'aws', 'azure', 'gcp']):
        return 12  # Cloud Computing
    if any(word in course_lower for word in ['devops', 'ci/cd', 'docker', 'kubernetes']):
        return 13  # DevOps
    if any(word in course_lower for word in ['inginerie software', 'design patterns', 'arhitectură software']):
        return 14  # Inginerie Software
    if any(word in course_lower for word in ['testare', 'selenium', 'qa']):
        return 15  # Testare Software
    if any(word in course_lower for word in ['robotică', 'iot', 'embedded']):
        return 16  # Robotică
    if any(word in course_lower for word in ['electronică', 'circuit', 'arduino', 'raspberry']):
        return 17  # Electronică
    if any(word in course_lower for word in ['mecanică', 'inginerie mecanică']):
        return 20  # Inginerie Mecanică
    if any(word in course_lower for word in ['matematică', 'algebră', 'calcul']):
        return 20  # Matematică Aplicată
    if 'fizică' in course_lower:
        return 21  # Fizică
    if 'chimie' in course_lower:
        return 22  # Chimie
    if any(word in course_lower for word in ['biologie', 'anatomie', 'botanică', 'zoologie']):
        return 23  # Biologie
    if any(word in course_lower for word in ['medicină', 'farmacologie', 'stomatologie', 'nursing']):
        return 24  # Medicină
    if 'psihologie' in course_lower:
        return 26  # Psihologie
    if 'sociologie' in course_lower:
        return 27  # Sociologie
    if any(word in course_lower for word in ['economie', 'microeconomie', 'macroeconomie']):
        return 28  # Economie
    if any(word in course_lower for word in ['finanțe', 'investiții', 'bursier']):
        return 29  # Finanțe
    if 'contabilitate' in course_lower:
        return 30  # Contabilitate
    if any(word in course_lower for word in ['management', 'leadership', 'project management', 'agile', 'scrum']):
        return 31  # Management
    if any(word in course_lower for word in ['marketing', 'seo', 'digital marketing', 'social media']):
        return 32  # Marketing
    if any(word in course_lower for word in ['resurse umane', 'recrutare']):
        return 33  # Resurse Umane
    if any(word in course_lower for word in ['antreprenoriat', 'startup']):
        return 34  # Antreprenoriat
    if any(word in course_lower for word in ['comerț', 'e-commerce', 'dropshipping']):
        return 35  # Comerț
    if 'logistică' in course_lower:
        return 36  # Logistică
    if any(word in course_lower for word in ['turism']):
        return 38  # Turism
    if any(word in course_lower for word in ['hotelărie', 'ospitalitate']):
        return 39  # Hotelărie
    if any(word in course_lower for word in ['gastronomie', 'patiserie', 'siguranță alimentară']):
        return 40  # Gastronomie
    if any(word in course_lower for word in ['agricultură', 'horticultură']):
        return 41  # Agricultură
    if any(word in course_lower for word in ['ecologie', 'mediu', 'climatice']):
        return 43  # Ecologie
    if 'geografie' in course_lower:
        return 45  # Geografie
    if any(word in course_lower for word in ['istorie']):
        return 46  # Istorie
    if any(word in course_lower for word in ['filosofie', 'etică']):
        return 47  # Filosofie
    if any(word in course_lower for word in ['literatură', 'scris']):
        return 48  # Literatură
    if any(word in course_lower for word in ['lingvistică', 'gramatică', 'ielts', 'toefl']):
        return 49  # Lingvistică
    if 'engleză' in course_lower:
        return 50  # Limba Engleză
    if any(word in course_lower for word in ['arte plastice', 'design grafic', 'photoshop', 'illustrator']):
        return 55  # Design Grafic
    if 'design interior' in course_lower:
        return 56  # Design Interior
    if 'arhitectură' in course_lower:
        return 57  # Arhitectură
    if 'construcții' in course_lower:
        return 58  # Construcții
    if any(word in course_lower for word in ['drept', 'penal', 'civil', 'internațional']):
        return 60  # Drept
    if any(word in course_lower for word in ['sport', 'fitness', 'alergare']):
        return 73  # Sport
    if 'nutriție' in course_lower:
        return 76  # Nutriție
    if any(word in course_lower for word in ['sănătate publică', 'primul ajutor']):
        return 77  # Sănătate Publică
    if 'stomatologie' in course_lower:
        return 78  # Stomatologie
    if any(word in course_lower for word in ['muzică', 'pian', 'chitară', 'canto', 'dj']):
        return 72  # Muzică
    if 'fotografie' in course_lower:
        return 69  # Fotografie
    if any(word in course_lower for word in ['video', 'premiere', 'after effects']):
        return 70  # Video Production
    if any(word in course_lower for word in ['cinema', 'producție film', 'scenarist']):
        return 71  # Cinema
    if any(word in course_lower for word in ['jurnalism', 'podcast']):
        return 67  # Jurnalism
    return 1  # Default: Tehnologia Informației

cursuriArray = {course: get_domain(course) for course in [
    "Introducere în programarea Python",
    "Dezvoltare Python avansată",
    "Fundamente Java",
    "Programare orientată pe obiecte cu Java",
    "C++ pentru începători",
    "Tehnici avansate C++",
    "Elemente esențiale JavaScript",
    "Dezvoltare web modernă",
    "Stăpânirea HTML5 și CSS3",
    "Dezvoltare web Full Stack",
    "Fundamente baze de date SQL",
    "Principii de proiectare a bazelor de date",
    "Structuri de date și algoritmi",
    "Bazele programării competitive",
    "Elemente esențiale Git și GitHub",
    "Bazele liniei de comandă Linux",
    "Fundamente de rețelistică",
    "Fundamente de securitate cibernetică",
    "Introducere în ethical hacking",
    "Bazele testării de penetrare",
    "Elemente esențiale de criminalistică digitală",
    "Fundamente cloud computing",
    "Fundamente AWS",
    "Bazele Microsoft Azure",
    "Elemente esențiale Google Cloud Platform",
    "Docker și containerizare",
    "Kubernetes pentru începători",
    "Elemente esențiale DevOps",
    "Fundamente pipeline CI/CD",
    "Dezvoltare API cu REST",
    "Fundamente GraphQL",
    "Dezvoltare aplicații mobile Android",
    "Curs complet Android Studio",
    "Bazele programării Kotlin",
    "Elemente esențiale Swift",
    "Dezvoltare aplicații iOS",
    "Fundamente Flutter",
    "Bazele React Native",
    "Dezvoltare jocuri cu Unity",
    "Fundamente Unity 3D",
    "Bazele Unreal Engine",
    "Blender pentru începători",
    "Fundamente modelare 3D",
    "Bazele animației",
    "Principii UI/UX Design",
    "Elemente esențiale Adobe Photoshop",
    "Bazele Adobe Illustrator",
    "Fundamente design grafic",
    "Stăpânirea Canva",
    "Editare video cu Premiere Pro",
    "Fundamente After Effects",
    "Bazele motion graphics",
    "Fundamente inteligență artificială",
    "Bazele machine learning",
    "Fundamente deep learning",
    "Introducere în rețele neuronale",
    "Elemente esențiale computer vision",
    "Bazele procesării limbajului natural",
    "Fundamente data science",
    "Analiza datelor cu Python",
    "Fundamente vizualizare date",
    "Tableau pentru începători",
    "Elemente esențiale Power BI",
    "Tehnici avansate Excel",
    "Bazele analizei de business",
    "Fundamente statistică",
    "Elemente esențiale probabilitate",
    "Bazele algebrei liniare",
    "Calcul diferențial și integral I",
    "Matematică discretă",
    "Fundamente algebră",
    "Elemente esențiale geometrie",
    "Fundamente fizică",
    "Bazele chimiei",
    "Fundamente biologie",
    "Bazele anatomiei umane",
    "Știința mediului",
    "Fundamente astronomie",
    "Mecanică inginerească",
    "Bazele ingineriei civile",
    "Fundamente inginerie electrică",
    "Elemente esențiale inginerie mecanică",
    "Fundamente robotică",
    "Bazele Internet of Things",
    "Introducere în sisteme embedded",
    "Fundamente blockchain",
    "Bazele criptomonedelor",
    "Introducere în Web3",
    "Fundamente antreprenoriat",
    "Bazele startup-urilor",
    "Principii de management al afacerilor",
    "Dezvoltarea abilităților de leadership",
    "Elemente esențiale project management",
    "Metodologii Agile",
    "Fundamente Scrum",
    "Bazele product management",
    "Fundamente marketing",
    "Elemente esențiale digital marketing",
    "Marketing pe rețele sociale",
    "Bazele content marketing",
    "Fundamente SEO",
    "Elemente esențiale email marketing",
    "Bazele brandingului",
    "Fundamente e-commerce",
    "Bazele dropshippingului",
    "Fundamente finanțe",
    "Bazele finanțelor personale",
    "Fundamente investiții",
    "Bazele pieței bursiere",
    "Elemente esențiale contabilitate",
    "Bazele contabilității financiare",
    "Contabilitate managerială",
    "Fundamente economie",
    "Bazele microeconomiei",
    "Fundamente macroeconomie",
    "Bazele dreptului afacerilor",
    "Managementul resurselor umane",
    "Fundamente recrutare",
    "Abilități de comunicare",
    "Elemente esențiale vorbire în public",
    "Abilități de negociere",
    "Gândire critică",
    "Tehnici de rezolvare a problemelor",
    "Elemente esențiale managementul timpului",
    "Productivitate la nivel avansat",
    "Inteligență emoțională",
    "Bazele dezvoltării carierei",
    "Masterclass redactare CV",
    "Pregătire pentru interviu",
    "Fundamente freelancing",
    "Elemente esențiale lucru la distanță",
    "Bazele serviciului clienți",
    "Fundamente vânzări",
    "Elemente esențiale copywriting",
    "Bazele redactării tehnice",
    "Atelier de scriere creativă",
    "Fundamente gramatică engleză",
    "Bazele redactării academice",
    "Pregătire IELTS",
    "Pregătire TOEFL",
    "Spaniolă pentru începătători",
    "Bazele limbii franceze",
    "Germană pentru începători",
    "Elemente esențiale italiană",
    "Fundamente japoneză",
    "Bazele limbii coreene",
    "Chineză pentru începători",
    "Bazele limbii ruse",
    "Fundamente psihologie",
    "Introducere în sociologie",
    "Bazele filosofiei",
    "Fundamente etică",
    "Bazele științelor politice",
    "Relații internaționale",
    "Istoria Europei",
    "Elemente esențiale istorie mondială",
    "Bazele istoriei artei",
    "Fundamente teoria muzicii",
    "Pian pentru începătători",
    "Bazele chitarei",
    "Fundamente canto",
    "Bazele fotografiei",
    "Fotografie portret",
    "Fotografie de peisaj",
    "Bazele producției de film",
    "Fundamente scenaristică",
    "Bazele jurnalismului",
    "Producție podcast",
    "Creare de conținut pentru social media",
    "Branding personal",
    "Fundamente meditație",
    "Yoga pentru începătători",
    "Bazele nutriției",
    "Fundamente fitness",
    "Elemente esențiale antrenament alergare",
    "Bazele științei sportului",
    "Fundamente volei",
    "Bazele baschetului",
    "Fundamente fotbal",
    "Bazele primului ajutor",
    "Fundamente sănătate publică",
    "Bazele nursingului",
    "Terminologie medicală",
    "Bazele farmacologiei",
    "Introducere în stomatologie",
    "Bazele medicinei veterinare",
    "Fundamente drept",
    "Bazele dreptului penal",
    "Drept internațional",
    "Drept constituțional",
    "Bazele proprietății intelectuale",
    "Fundamente imobiliare",
    "Bazele arhitecturii",
    "Elemente esențiale design interior",
    "Bazele designului vestimentar",
    "Fundamente textile",
    "Bazele artelor culinare",
    "Fundamente patiserie și panificație",
    "Elemente esențiale siguranță alimentară",
    "Management hotelier și ospitalitate",
    "Fundamente turism",
    "Bazele managementului evenimentelor",
    "Managementul lanțului de aprovizionare",
    "Fundamente logistică",
    "Management operațional",
    "Bazele managementului calității",
    "Lean Six Sigma",
    "Fundamente producție industrială",
    "Bazele achizițiilor",
    "Management retail",
    "Fundamente CRM",
    "Bazele SAP",
    "Elemente esențiale Oracle Database",
    "Fundamente MongoDB",
    "Baze de date NoSQL",
    "Bazele Firebase",
    "Elemente esențiale Redis",
    "PHP pentru începători",
    "Fundamente Laravel",
    "Bazele Node.js",
    "Elemente esențiale Express.js",
    "Fundamente React.js",
    "Bazele Vue.js",
    "Fundamente Angular",
    "Elemente esențiale Next.js",
    "Bazele Svelte",
    "Fundamente TypeScript",
    "Bazele Tailwind CSS",
    "Elemente esențiale Bootstrap",
    "Fundamente Sass",
    "Bazele accesibilității web",
    "Design web responsive",
    "Aplicații web progresive",
    "Bazele testării software",
    "Fundamente automatizare QA",
    "Elemente esențiale Selenium",
    "Test-Driven Development",
    "Principii Clean Code",
    "Bazele arhitecturii software",
    "Fundamente design patterns",
    "Arhitectură microservicii",
    "Bazele system design",
    "Fundamente sisteme de operare",
    "Arhitectura calculatoarelor",
    "Bazele limbajului Assembly",
    "Introducere în proiectarea compilatoarelor",
    "Programare paralelă",
    "Elemente esențiale multithreading",
    "Bazele programării funcționale",
    "Fundamente Rust",
    "Bazele programării Go",
    "Elemente esențiale Perl",
    "Bazele programării Ruby",
    "Fundamente Django",
    "Elemente esențiale Flask",
    "Bazele FastAPI",
    "Cyber Threat Intelligence",
    "Bazele analizei malware",
    "Reverse Engineering",
    "Fundamente Blue Team",
    "Operațiuni Red Team",
    "Training SOC Analyst",
    "Fundamente SIEM",
    "Bazele apărării rețelelor",
    "Practici de secure coding",
    "Bazele criptografiei",
    "Managementul securității informației",
    "Fundamente managementul riscurilor",
    "Elemente esențiale conformitate",
    "Bazele GDPR",
    "Transformare digitală",
    "Managementul inovației",
    "Fundamente Design Thinking",
    "Bazele strategiei de business",
    "Finanțe corporative",
    "Fundamente finanțare startup",
    "Bazele venture capital",
    "Business Intelligence",
    "Elemente esențiale luarea deciziilor",
    "Change Management",
    "Comportament organizațional",
    "Rezolvarea conflictelor",
    "Elemente esențiale team building",
    "Fundamente coaching",
    "Abilități de mentorat",
    "Bazele metodelor de cercetare",
    "Redactare academică de cercetare",
    "Fundamente proiectarea sondajelor",
    "Analiză statistică cu R",
    "Bazele programării R",
    "Fundamente MATLAB",
    "Elemente esențiale SPSS",
    "Fundamente GIS",
    "Sisteme informaționale geografice",
    "Bazele quantum computing",
    "Elemente esențiale bioinformatică",
    "Fundamente genetică",
    "Bazele biologiei moleculare",
    "Introducere în neuroștiințe",
    "Bazele științei cognitive",
    "Fundamente energie regenerabilă",
    "Bazele energiei solare",
    "Elemente esențiale sustenabilitate",
    "Studii despre schimbările climatice",
    "Bazele managementului deșeurilor",
    "Fundamente agricultură",
    "Bazele agriculturii ecologice",
    "Elemente esențiale horticultură",
    "Bazele biologiei marine",
    "Fundamente zoologie",
    "Bazele botanicii",
    "Elemente esențiale paleontologie",
    "Fundamente arheologie",
    "Bazele antropologiei",
    "Studii culturale",
    "Fundamente media studies",
    "Bazele studiilor cinematografice",
    "Analiză literară",
    "Atelier de scriere poezie",
    "Elemente esențiale storytelling",
    "Benzi desenate și ilustrație",
    "Bazele character design",
    "Fundamente game design",
    "Bazele level design",
    "Elemente esențiale sound design",
    "Bazele producției muzicale",
    "Fundamente DJ",
    "Bazele Ableton Live",
    "Elemente esențiale FL Studio",
    "Bazele Logic Pro",
    "Fundamente cyber law",
    "Bazele protecției datelor",
    "Open Source Intelligence",
    "Tehnici OSINT",
    "Fundamente cloud security",
    "Identity and Access Management",
    "Bazele endpoint security",
    "Elemente esențiale wireless networking",
    "Pregătire CCNA",
    "Fundamente CCNP",
    "Bazele network automation",
    "Python pentru rețelistică",
    "Fundamente Bash scripting",
    "Bazele PowerShell",
    "Administrare Windows Server",
    "Elemente esențiale Active Directory",
    "Fundamente virtualizare",
    "Bazele VMware",
    "Elemente esențiale Hyper-V",
    "Fundamente help desk",
    "Bazele suportului IT",
    "Fundamente hardware",
    "Bazele asamblării PC-urilor",
    "Elemente esențiale troubleshooting",
    "Designul experienței clienților",
    "Fundamente service design",
    "Bazele strategiei de brand",
    "Elemente esențiale cercetare de piață",
    "Psihologia consumatorului",
    "Economie comportamentală",
    "Fundamente taxe și impozite",
    "Bazele payroll",
    "Elemente esențiale audit",
    "Guvernanță corporativă",
    "Etica afacerilor",
    "Management nonprofit",
    "Fundamente fundraising",
    "Elemente esențiale grant writing",
    "Fundamente community management",
    "Antreprenoriat social",
    "Administrație publică",
    "Fundamente guvernare",
    "Bazele diplomației",
    "Security Studies",
    "Managementul dezastrelor",
    "Fundamente crisis management",
    "Training răspuns de urgență",
    "Siguranța la locul de muncă",
    "Bazele sănătății ocupaționale",
    "Fundamente inginerie industrială",
    "Optimizarea proceselor",
    "Fundamente CAD",
    "Bazele AutoCAD",
    "Elemente esențiale SolidWorks",
    "Fundamente Revit",
    "Bazele BIM",
    "Management în construcții",
    "Bazele ingineriei structurale",
    "Fundamente hidraulică",
    "Bazele termodinamicii",
    "Mecanica fluidelor",
    "Fundamente știința materialelor",
    "Bazele nanotehnologiei",
    "Fundamente semiconductori",
    "Fundamente electronică",
    "Bazele proiectării circuitelor",
    "Elemente esențiale PCB Design",
    "Fundamente Arduino",
    "Bazele Raspberry Pi",
    "Bazele tehnologiei dronelor",
    "Fundamente aerospațiale",
    "Bazele aviației",
    "Studii maritime",
    "Fundamente economie a ofertei",
    "Modelare financiară",
    "Bazele bankingului de investiții",
    "Matematică de business",
    "Fundamente știința actuarială",
    "Bazele asigurărilor",
    "Elemente esențiale analiza riscului",
    "Bazele dreptului consumatorului",
    "Fundamente drept contractual",
    "Redactare juridică",
    "Elemente esențiale mediere",
    "Fundamente dezvoltare personală",
    "Stăpânirea autodisciplinei",
    "Bazele formării obiceiurilor",
    "Elemente esențiale stabilirea obiectivelor",
    "Mindfulness pentru începătători",
    "Știința fericirii",
    "Tehnici de îmbunătățire a memoriei",
    "Învățarea cum să înveți",
    "Bazele citirii rapide",
    "Elemente esențiale creativitate",
    "Atelier de inovație",
    "Bazele parentingului",
    "Dezvoltarea copilului",
    "Metodologii de predare",
    "Managementul clasei",
    "Psihologie educațională",
    "Design instrucțional",
    "Dezvoltarea curriculumului",
    "Predare online",
    "Fundamente Moodle",
    "Administrare LMS",
    "Managementul învățământului superior",
    "Educație specială",
    "Educație timpurie",
    "Fundamente învățare pentru adulți",
    "Matematică pentru machine learning",
    "Etica inteligenței artificiale",
    "Bazele prompt engineering",
    "Elemente esențiale AI generativ",
    "Dezvoltarea chatbot-urilor",
    "Fundamente LLM (modele lingvistice mari)",
    "AI Product Management",
    "Bazele sistemelor de recomandare",
    "Învățare prin întărire",
    "Sisteme autonome",
    "Bazele mașinilor autonome",
    "Interogări SQL avansate",
    "Administrarea bazelor de date",
    "Fundamente data warehousing",
    "Bazele ETL",
    "Analiză big data",
    "Fundamente Hadoop",
    "Bazele Apache Spark",
    "Fundamente Kafka",
    "Ingineria datelor",
    "Fundamente MLOps",
    "Feature engineering",
    "Implementarea modelelor ML",
    "Edge computing",
    "Cloud serverless",
    "Fundamente SaaS",
    "Design produse SaaS",
    "Administrare CRM",
    "Fundamente ERP",
    "Modelarea proceselor de business",
    "Bazele UML",
    "Agile coaching",
    "Pregătire Scrum Master",
    "Fundamente Product Owner",
    "Bazele Kanban",
    "Metodologia Lean Startup",
    "Growth hacking",
    "Influencer marketing",
    "Fundamente affiliate marketing",
    "Marketing mobil",
    "Bazele PPC advertising",
    "Fundamente Google Ads",
    "Elemente esențiale Meta Ads",
    "Marketing TikTok",
    "Strategie YouTube",
    "Marketing podcast",
    "Construirea comunităților",
    "Fundamente securitate web",
    "Dezvoltare web securizată",
    "OWASP Top 10",
    "Bazele securității API",
    "Modelarea amenințărilor",
    "Evaluarea vulnerabilităților",
    "Training SOC",
    "Răspuns la incidente",
    "Backup și recuperare",
    "Planificare disaster recovery",
    "Bazele arhitecturii enterprise",
    "Alfabetizare digitală",
    "Introducere în programare",
    "Fundamente știința calculatoarelor",
]}

import random

# First names and surnames from studenti.py
first_names = {name: get_domain(name) for name in [
    "Constantin",
    "Nicolae",
    "Dan",
    "Eduard",
    "Pavel",
    "Adriana",
    "Ion",
    "Patricia",
    "Alexandru",
    "Sergiu",
    "Vladislav",
    "Marin",
    "Salomeia",
    "Oxana",
    "Virineea",
    "Dragoș",
    "Ecaterina",
    "Alexandrina",
    "Alexandra",
    "Maxim",
    "Petru",
    "Remos",
    "Bogdan",
    "Gabriel",
    "Artemie",
    "Artiom",
    "Serghei",
    "Daniel",
    "Mădălina",
    "Damian",
    "Gabriela",
    "Denis",
    "Dumitru",
    "Elvis",
    "Andrian",
    "Mihail",
    "Mihai",
    "Mihaela",
    "Mirela",
    "Valentina",
    "Valeriu",
    "Valeria",
    "Vlad",
    "Vladimir",
    "Tudor",
    "Andrei",
    "Andreea",
    "Nicoleta",
    "Aliona",
    "Stela",
    "Ștefan",
    "Ștefania",
    "Svetlana",
    "Diana",
    "Dorina",
    "Dorin",
    "Dorel",
    "Artur",
    "Vera",
    "Viorica",
    "Veaceslav",
    "Vasile",
    "Marcel",
    "Valentin",
    "Iulia",
    "Iulian",
    "Iuliana",
    "Violeta",
    "Ghenadie",
    "Iulian-Albert",
    "Octavian",
    "Sorin",
    "Marionela",
    "Nadejda",
    "Adelina",
    "Adrian",
    "Georgiana",
    "Giorgiana",
    "Igor",
    "Anastasia",
    "Ana-Maria",
    "Dumitrița",
    "Robert",
    "Roxana",
    "Ruslan",
    "Eugen",
    "Eugeniu",
    "Eugenia",
    "Evelina",
    "Fiodor",
    "Irina",
    "Loredana",
    "Tatiana",
    "Ivan",
    "Marina",
    "Marius",
    "Maria",
    "Ovidiu",
    "Oleg",
    "Olga",
    "Viorel",
    "Laurențiu",
    "Larisa",
    "Vlada",
    "Radu",
    "Catarina",
    "Daria",
    "Efimia",
    "Efim",
    "Cristina",
    "Cristian",
    "Cristi",
    "Dinuț",
    "Nichita",
    "Nikita",
    "Augustin",
    "Augustina",
    "Aurel",
    "Aurelia",
    "Liviu",
    "Laura",
    "Lavinia",
    "Liliana",
    "Alexei",
    "Alexia",
    "Alex",
    "Xenia",
    "Vadim",
    "Iaroslav",
    "Lucian",
    "Luciana",
    "Teodor",
    "Teodora",
    "Chiril",
    "Ilie",
    "Ioana",
    "Ionela",
    "Eremia",
    "Ana",
    "Beatrice",
    "Sofia",
    "Liuba",
]}

surnames = [
    "Achiruș",
    "Batițchi",
    "Beșliu",
    "Bragari",
    "Caraman",
    "Ciutac",
    "Cîrlan",
    "Comanac",
    "Corciu",
    "Crețu",
    "Găină",
    "Gojan",
    "Grigoriță",
    "Istrati",
    "Jumiga",
    "Macari",
    "Medinschi",
    "Miron",
    "Mironova",
    "Munteanu",
    "Nedelco",
    "Nicolai",
    "Nitrean",
    "Orlețchi",
    "Pascaru",
    "Poclitar",
    "Postoroncă",
    "Prijilevschi",
    "Roman",
    "Sava",
    "Stepan",
    "Stici",
    "Tilipeț",
    "Arion",
    "Babără",
    "Rusu",
    "Ceban",
    "Ciobanu",
    "Țurcan",
    "Cebotari",
    "Lungu",
    "Sîrbu",
    "Popa",
    "Rotari",
    "Guțu",
    "Ursu",
    "Roșca",
    "Melnic",
    "Bălan",
]



# Generate coordinators
first_names_list = list(first_names.keys())
coordinators = [f"{sn} {fn}" for sn in surnames for fn in first_names_list]
random.shuffle(coordinators)

# Generate inserts and print to terminal
values = []
for i, (course, domeniu) in enumerate(cursuriArray.items(), 1):
    limba = random.choices(['Română', 'Engleză', 'Rusă', 'Franceză'], weights=[40, 40, 10, 10])[0]
    tip = random.choice(['Online', 'Offline', 'Hibrid'])
    r = random.random()
    if r < 0.2:
        pret = 0.00
    elif r < 0.5:
        pret = random.randint(1, 49) * 100
    else:
        pret = random.randint(50, 100) * 100
    coord = coordinators.pop(0) if coordinators else "Default Coordinator"
    institutie = random.randint(1, 417)
    value = f"({i}, '{course}', '{limba}', '{tip}', {pret}, '{coord}', {domeniu}, {institutie})"
    values.append(value)

# Print single INSERT with all values
print("INSERT INTO Cursuri (CursID, DenumireCurs, LimbaPredare, TipPredare, PretCurs, Coordonator, DomeniuID, InstitutieID) VALUES")
print(",\n".join("    " + v for v in values) + ";")